name: Test & Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: fa
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        env:
          DATABASE_URL: postgres://fa:mysecretpassword@localhost:5432/finance_assistant_test
          PGHOST: localhost
        run: |
          ruby bin/rails db:test:prepare
          ruby bin/rails test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
